rfkill support, stolen from airmon-ng

diff --git a/blue_sonar b/blue_sonar
--- a/blue_sonar
+++ b/blue_sonar
@@ -26,6 +26,79 @@ usage() {
   printf "\n"
 }
 
+rfkill_check() {
+	#take phy and check blocks
+	if [ "${RFKILL}" = 0 ]; then
+		#immediately return if rfkill isn't supported
+		return 0
+	fi
+	if [ -z "${1}" ]; then
+		printf "Fatal, rfkill_check requires a phy to be passed in\n"
+		exit 1
+	fi
+	#first we have to find the rfkill index
+	#this is available as /sys/class/net/wlan0/phy80211/rfkill## but that's a bit difficult to parse
+	index="$(rfkill list | grep ${1} | awk -F: '{print $1}')"
+	if [ -z "$index" ]; then
+		return 187
+	fi
+	rfkill_status="$(rfkill list ${index} 2>&1)"
+	if [ $? != 0 ]; then
+		printf "rfkill error: ${rfkill_status}\n"
+		return 187
+	elif [ -z "${rfkill_status}" ]; then
+		printf "rfkill had no output, something went wrong.\n"
+		exit 1
+	else
+		soft=$(printf "${rfkill_status}" | grep -i soft | awk '{print $3}')
+		hard=$(printf "${rfkill_status}" | grep -i hard | awk '{print $3}')
+		if [ "${soft}" = "yes" ] && [ "${hard}" = "no" ]; then
+			return 1
+		elif [ "${soft}" = "no" ] && [ "${hard}" = "yes" ]; then
+			return 2
+		elif [ "${soft}" = "yes" ] && [ "${hard}" = "yes" ]; then
+			return 3
+		fi
+	fi
+	return 0
+}
+
+rfkill_unblock() {
+	#attempt unblock and CHECK SUCCESS
+	if [ "${RFKILL}" = 0 ]; then
+		#immediately return if rfkill isn't supported
+		return 0
+	fi
+	rfkill_status="$(rfkill unblock ${1#phy} 2>&1)"
+	if [ $? != 0 ]; then
+		rfkill_status="$(rfkill unblock $index 2>&1)"
+		if [ $? != 0 ]; then
+			if [ `echo "$blah" | grep "Usage" | wc -l` -eq 1 ]; then
+				printf "Missing parameters in rfkill! Report this"
+			else
+				printf "rfkill error: ${rfkill_status}\n"
+			fi
+			printf "Unable to unblock.\n"
+			return 1
+		fi
+	fi
+
+	sleep 1
+	return 0
+}
+
+yesorno() {
+	read input
+	case $input in
+		y) return 0 ;;
+		yes) return 0 ;;
+		n) return 1 ;;
+		no) return 1 ;;
+		*) printf "\nInvalid input. Yes, or no? [y/n] "
+		   yesorno;;
+	esac
+}
+
 readonly PROGRESS='#####################################################################'
 readonly red=$'\e[0;31m'
 readonly end=$'\e[0m'
@@ -122,14 +195,48 @@ if [ -z "${target}" ] && [ "${sim}" != "1" ]; then
   exit 1
 fi
 
-
 trap control_c INT
 trap control_c TERM
+
+rfkill_check ${radio}
+rfkill_retcode="$?"
+case ${rfkill_retcode} in
+  1) printf "\t${radio} is soft blocked, please run \"rfkill unblock ${index}\" to use this interface.\n" ;;
+  2) printf "\t${radio} is hard blocked, please flip the hardware wifi switch (or in BIOS) to on.\n"
+    printf "\tIt may also be possible to unblock with \"rfkill unblock ${index}\"\n"
+    ;;
+  3) printf "\t${radio} is hard and soft blocked, please flip the hardware wifi switch to on.\n"
+    printf "\tIt may also be needed to unblock with \"rfkill unblock ${index}\"\n"
+    ;;
+esac
+if [ "${rfkill_retcode}" != 0 ]; then
+  printf "rfkill error, unable to start ${radio}\n\n"
+  printf "Would you like to try and automatically resolve this? [y/n] "
+  yesorno
+  retcode="$?"
+  if [ "${retcode}" = "1" ]; then
+    return 1
+  elif [ "${retcode}" = "0" ]; then
+    rfkill_unblock ${PHYDEV}
+  fi
+fi
 
 if [ -x "$(command -v rc-service 2>&1)" ]; then
   rc-service bluetooth status > /dev/null 2>&1 || rc-service bluetooth start > /dev/null 2>&1
 elif [ -x "$(command -v service)" ]; then
   service bluetooth status > /dev/null 2>&1 || service bluetooth start > /dev/null 2>&1
+fi
+
+if [ -c /dev/rfkill ]; then
+	if [ ! -x "$(command -v rfkill 2>&1)" ];then
+		printf "Your kernel supports rfkill but you don't have rfkill installed.\n"
+		printf "To ensure devices are unblocked you must install rfkill.\n"
+		RFKILL=0
+	else
+		RFKILL=1
+	fi
+else
+	RFKILL=0
 fi
 
 while true; do
